LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libmdmdetect
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS := optional

LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_OWNER := qcom
LOCAL_MULTILIB := 32

LOCAL_SRC_FILES := mdm_detect.c

LOCAL_EXPORT_C_INCLUDE_DIRS := $(LOCAL_PATH)

include $(BUILD_SHARED_LIBRARY)
